[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "brunamy", email = "bm6952@gmail.com"},
]
dependencies = [
    "django>=4.2.4",
]
requires-python = ">=3.10"
license = {text = "bruna miranda"}
